"""init

Revision ID: 00f0ad9b9987
Revises: 
Create Date: 2021-08-14 13:41:23.822345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f0ad9b9987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_type', sa.String(length=30), nullable=True),
    sa.Column('insert_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=128), nullable=False),
    sa.Column('store_area', sa.String(length=128), nullable=True),
    sa.Column('Testing create time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('user_tag_rel',
    sa.Column('tag_rt', sa.Integer(), nullable=True),
    sa.Column('user_rt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_rt'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_rt'], ['users.id'], )
    )
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    op.drop_table('user_tag_rel')
    op.drop_table('stores')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
