"""set_cloumn

Revision ID: 0e398af7eed1
Revises: 5dad3e15662a
Create Date: 2021-08-29 13:46:53.041202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e398af7eed1'
down_revision = '5dad3e15662a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_address')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True))
        batch_op.drop_column('Testing create time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Testing create time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_column('create_time')

    op.create_table('user_address',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='user_address_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_address_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('address')
    # ### end Alembic commands ###
