"""init

Revision ID: 55f3553ecbae
Revises: 3aeb52257c2c
Create Date: 2021-08-15 15:15:18.993543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f3553ecbae'
down_revision = '3aeb52257c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
