"""set_age_default

Revision ID: 5dad3e15662a
Revises: 7011ad2a4309
Create Date: 2021-08-15 19:31:18.442786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dad3e15662a'
down_revision = '7011ad2a4309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
